FROM debian:latest

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY ./trigger-warning/pi/ ./

# Install app dependencies
RUN apt update && apt upgrade --yes
RUN apt install --yes python3 python3-pip
RUN ln -sf python3 /usr/bin/python
RUN pip3 install --upgrade gpiozero pigpio

# Run the app
CMD [ "python3", "app.py" ]