services:
  amnesia:
    image: ghcr.io/mryachanin/amnesia:main
    hostname: amnesia
    env_file:
      - ./amnesia/database.env
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
    restart: unless-stopped
  sleep-apnea:
    depends_on:
      - amnesia
    image: ghcr.io/mryachanin/sleep-apnea:main
    ports:
      - 8080:8080
volumes:
  database-data: