services:
  amnesia:
    build:
      context: ${PWD}
      dockerfile: Dockerfile.amnesia
    hostname: amnesia
    env_file:
      - ./amnesia/database.env
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
    restart: unless-stopped
  sleep-apnea:
    depends_on:
      - amnesia
    build:
      context: ${PWD}
      dockerfile: Dockerfile.sleep-apnea
    ports:
      - 8080:8080
volumes:
  database-data: